# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20160114_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Empty post', verbose_name='Content'),
        ),
    ]
